=== Lynx4685/seed/schema/jobpack.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "version": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "author_name": {
        "type": "string"
      },
      "author_url": {
        "type": "string"
      },
      "timeout": {
        "type": "integer"
      },
      "cpus_required": {
        "type": "number"
      },
      "mem_required": {
        "type": "number"
      },
      "disk_out_const_required": {
        "type": "number"
      },
      "disk_out_mult_required": {
        "type": "number"
      },
      "interface": {
        "type": "object",
        "properties": {
          "output_data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "media_type": {
                  "type": "string"
                },
                "required": {
                  "type": "boolean",
                  "default": true
                },
                "type": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "glob": {
                  "type": "string"
                }
              },
              "required": [
                "media_type",
                "type",
                "name",
                "glob"
              ]
            }
          },
          "command_arguments": {
            "type": "string"
          },
          "input_data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "media_types": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "required": {
                  "type": "boolean"
                },
                "type": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                }
              },
              "required": [
                "media_types",
                "required",
                "type",
                "name"
              ]
            }
          },
          "command": {
            "type": "string"
          }
        },
        "required": [
          "output_data",
          "command_arguments",
          "input_data",
          "command"
        ]
      },
      "error_mapping": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "code": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "category": {
              "type": "string",
              "enum": [
                "ALGORITHM",
                "DATA",
                "SYSTEM"
              ]
            }
          },
          "required": [
            "code",
            "name",
            "title",
            "description",
            "category"
          ]
        }
      }
    },
    "required": [
      "name",
      "version",
      "title",
      "description",
      "author_name",
      "author_url",
      "timeout",
      "cpus_required",
      "mem_required",
      "disk_out_const_required",
      "disk_out_mult_required",
      "interface",
      "error_mapping"
    ]
  }
}

=== Lynx4685/seed/examples/jobpack-full.json
[
  {
    "name": "my-algorithm",
    "version": "1.0.0",
    "title": "My first algorithm",
    "description": "Reads an HDF5 file and outputs two TIFF images and a CSV",
    "author_name": "John_Doe",
    "author_url": "http://www.example.com",
    "timeout": 3600,
    "cpus_required": 10.0,
    "mem_required": 10240.0,
    "disk_out_const_required": 0.0,
    "disk_out_mult_required": 0.0,
    "interface": {
      "output_data": [
        {
          "media_type": "image/tiff",
          "required": true,
          "type": "file",
          "name": "output_file_tif",
          "glob": "outfile1*.tif"
        },
        {
          "media_type": "image/tiff",
          "required": true,
          "type": "file",
          "name": "output_file_tif2",
          "glob": "outfile2*.tif"
        },
        {
          "media_type": "text/csv",
          "required": true,
          "type": "file",
          "name": "output_file_csv",
          "glob": "outfile*.csv"
        }
      ],
      "command_arguments": "${input_file} ${job_output_dir}",
      "input_data": [
        {
          "media_types": [
            "image/x-hdf5-image"
          ],
          "required": true,
          "type": "file",
          "name": "input_file"
        }
      ],
      "command": "/app/my_wrapper.sh"
    },
    "error_mapping": [
      {
        "code": 1,
        "name": "ErrorName",
        "title": "Error Title",
        "description": "Error Description",
        "category": "SYSTEM"
      },
      {
        "code": 2,
        "name": "ErrorName",
        "title": "Error Title",
        "description": "Error Description",
        "category": "DATA"
      },
      {
        "code": 3,
        "name": "ErrorName",
        "title": "Error Title",
        "description": "Error Description",
        "category": "ALGORITHM"
      }
    ]
  }
]
